when@dev:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            collect_serializer_data: true
            enabled: false

when@test:
    framework:
        profiler: { collect: false }
